### ISSUE TITLE
scull pipe.c

### ISSUE THREAD

**Issue by quelotic** [martinezjavier/ldd3#24]
scull's pipe.c does not compile on 4.11.9, with GCC 7.1.1

error: implicit declaration of function ‘signal_pendin ’; did you mean ‘timer_pending’? [-Werror=implicit-function-declaration]
   if (signal_pending(current))
       ^~~~~~~~~~~~~~
       timer_pending

**Comment by nuaalida** [comment]
You should add a header fie 
`#include <linux/sched/signal.h>`

You should search on the Bootlin website for missing header file error.
