### ISSUE TITLE
scullc does not build properly

### ISSUE THREAD

**Issue by davmaz** [martinezjavier/ldd3#35]
Thanks for this page! If I make in ldd3-master/scull, everything works as is should. However, if I cd to ldd3-master/scullc, make err's out  starting with 
error: implicit declaration of function ‘aio_complete’ ...

Am I missing something?

**Comment by davmaz** [comment]
As per README, exported KERNELDIR=/lib/modules/`uname -r`/build
(it's /lib/modules/4.15.0-50-generic/build) followed by make. It built all/most of the modules but stopped in scullc. I've attached a complete listing.

Thanks for any guidance!
[Errors.txt](https://github.com/martinezjavier/ldd3/files/3241940/Errors.txt)

**Comment by dwalkes** [comment]
Work in progress changes on 4.18 at https://github.com/cu-ecen-5013/ldd3/tree/scullc-4-18-ubuntu - this version compiles but hasn't yet implemented the aio_read and aio_write replacements, see comment link for an example which could be used as a reference.

Note that the aio_read and aio_write implementations in sculld, scullp, and scullv will all have the same problems.

**Comment by dwalkes** [comment]
I have an implementation that's compiling and I believe is correct, see https://github.com/cu-ecen-5013/ldd3 and https://github.com/cu-ecen-5013/ldd3/commit/7b7492ae31738df83176d8edb4becbc4faf17cad.  Compile succeeds and the driver runs but I haven't specifically tested non blocking IO.  Test help is welcome.

**Comment by dwalkes** [comment]
Should be resolved in #39
